Link with zlib for newer AWS SDK
Otherwise, the linker throws errors:

/usr/bin/ld: aws-sdk-cpp/inst/lib/libaws-cpp-sdk-core.a(ub_core.cpp.o): undefined reference to symbol 'inflateEnd'
/usr/bin/ld: /lib/x86_64-linux-gnu/libz.so.1: error adding symbols: DSO missing from command line